### ISSUE TITLE
The domain io does not exist

### ISSUE THREAD

**Issue by mediosam** [baptistecdr/docker-gandyn#201]
hello, i dont know if it s on the parsing or anything else. but it does not find the domain finishing by .io

<img width="562" alt="Capture d’écran 2024-03-17 à 10 52 37" src="https://github.com/baptistecdr/docker-gandyn/assets/6317848/f65d75e3-51ee-4f9e-92c7-01dfabdc4ee1">

the container is running on synology and the config.ini file seems to be ok.
Thank you for your help

**Comment by baptistecdr** [comment]
Hello @mediosam ,

Unless it is a problem with the containerization, it is out of my hands, I'm just packaging https://github.com/Danamir/dyn-gandi inside a container. Although it seems abandoned...

**Comment by mediosam** [comment]
Hello,
So d’ont waist time on it, i Will try another solution.
Thank you for your Quick response

Regards
